### ISSUE TITLE
Ambiguous instance for <> coming from Data.Monoid and Diagrams.Prelude

### ISSUE THREAD

**Issue by hasanalrasyid** [diagrams/diagrams-builder#35]
stack: lts-11.9

perhaps this was already expected. So, (<>) are defined in both Data.Monoid and Diagrams.Prelude.
My workaround is actually just to remove the "Data.Monoid" in setDiagramsImports.
I do not know if this is a good solution or not.
I create this issue to raise awareness and hopefully the solution would be integrated into the main branch.
So that I can remove my local repo of diagrams-builder. Thank you very much for your consideration.

**Comment by byorgey** [comment]
Hi @hasanalrasyid , thanks for the report!  Note, `Diagrams.Prelude` actually does not define `(<>)`, it simply re-exports it from `Data.Semigroup`.  I think perhaps we should probably change `Data.Monoid` in `setDiagramsImports` to `Data.Semigroup` instead.  I am not 100% sure though, I have not thought about this for quite a while.

**Comment by hasanalrasyid** [comment]
Hi @byorgey, thanks for the response.

Perhaps this issue is related with this proposal
https://gitlab.haskell.org/ghc/ghc/-/wikis/proposal/semigroup-monoid

If that is the case, maybe there is a need to first consider how far back the support for older ghc (or in this case, lts version). 

Actually, I stumbled into this issue after I updated the lts version (as required by another library).
