### ISSUE TITLE
doesn't accept lens-5.3

### ISSUE THREAD

**Issue by ysangkok** [diagrams/diagrams-builder#37]
as you can see in this issue from May:

* https://github.com/commercialhaskell/stackage/issues/7408

diagrams-builder needs to have it's upper bound on lens bumped

**Comment by byorgey** [comment]
Thanks for the nudge.  I've been slowly working my way through getting diagrams packages updated, hope to get to this one soon.

**Comment by byorgey** [comment]
Just an update --- I've been waiting to update until `hint` supports GHC 9.10.  If anyone would really like a version of `diagrams-builder` that supports `lens-5.3` but not GHC 9.10 I could put out an interim release.

**Comment by ysangkok** [comment]
One issue with not supporting lens-5.3 is that Stackage already updated, so it had to remove diagrams-builder. Given that the next LTS will be out very soon, this means that diagrams-builder could miss a whole LTS release, even though the LTS is for GHC 9.8, not 9.10.

**Comment by byorgey** [comment]
Good point.  I've revised `diagrams-builder` on Hackage, and the revised version now builds with `lens-5.3` (as well as a few other upper bound bumps).
